### ISSUE TITLE
Scripts directory is missing from repository

### ISSUE THREAD

**Issue by juhtornr** [elixir-europe/human-data-beacon-ui#1]
It seems that 'scripts' directory is missing from this repository and repository can't be build as explained in README:

$ docker-compose -f deploy/beacon/docker-compose-beacon.yml build
...
Step 13 : COPY scripts ./scripts
ERROR: Service 'beacon_ui' failed to build: lstat scripts: no such file or directory

**Comment by malberich** [comment]
Thanks @juhtornr, You're right.

Actually there was a .gitignore entry that blocked the folder to be committed.

Now it's done. Gitignore entry removed, and scripts folder pushed.

Would you let me know if it works now for you? If so, feel free to close the issue.

**Comment by juhtornr** [comment]
Thanks for quick response! I was now able to build the project and this issue is resolved.

**Comment by malberich** [comment]
You're welcome, thanks for pointing to the missing piece. Don't hesitate to open new issues or open this one if needed.
