### ISSUE TITLE
Url for Java version not reachable 

### ISSUE THREAD

**Issue by SevKohler** [elixir-europe/human-data-beacon-ui#9]
https://github.com/ga4gh-beacon/beacon-ui-elixir/blob/49deb4c2fd1154cfda042e81f91dcd171fc20517/deploy/beacon/beacon_backend/Dockerfile#L9

**Comment by shiltemann** [comment]
Any update on this? I am trying to set up a beacon and running into the same problem trying to build the Docker images

Are the docker images published anywhere on e.g. Docker Hub or Quay?

**Comment by silverdaz** [comment]
Wow, I'm just seeing that issue now. Sorry for the delay!

The dockerfile points to an old java version.
It was a long time ago, we are not maintaining that repo anymore.

But I did some digging and I found the following:

The dockerfile is trying to build the [beacon image](https://github.com/ga4gh-beacon/beacon-elixir) and it is already [built on docker hub](https://hub.docker.com/repository/docker/egarchive/elixir-beacon). You can refer to them if you want.

You can, of course, update the Dockerfile from this repo and build the image locally with a valid jdk link. You should be good to go, but this is not the purpose of this repo. It was just used to demonstrate the beacon functionality during an Elixir seminar/presentation.

I think you are looking at the wrong place. There is a [java implementation of the Elixir Beacon](https://github.com/ga4gh-beacon/beacon-elixir), for version 1. We moved on to a [python implementation](https://github.com/CSCfi/beacon-python) (still for version 1, with a [UI too](https://github.com/EGA-archive/beacon-ui)), and more importantly, we moved on to [version 2](https://github.com/EGA-archive/beacon-2.x/)! We are not maintaining v1 anymore, neither the java implementation, nor the python implementation, nor the UIs.

We are not resolving the issue, I'm closing it, and I provided suggestions above on how to proceed.

**Comment by shiltemann** [comment]
@silverdaz thanks! I must admit it is a bit hard to make sense of all the different repos in various places, perhaps it would be an idea to add a line in the README directing people to the right place for the latest version?

I will continue with version2 then, thanks for the quick reply :+1:
